import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { loadTs } from './loadTs.mjs';
const {SECONDARY_LINES, resolveAvailableLines, secondaryLineDisplayName}=await loadTs('../src/modules/scenarioMods/secondaryLines.ts');
const sid='lcq.stage_04b_lingfei_baiyi_crisis';
const chat='lcq.event.zhu88_heimohai_chat';
const line=SECONDARY_LINES.find(x=>x.id==='heimohai');
test('heimohai anchor unchanged, public hint has no Zhu or poison-sect shortcut',()=>{
 assert.deepEqual(line.anchorEventIds,['lcq.event.s04b_lingfei_baiyi_crisis_04']);
 assert.equal(line.anchorCharacterIds,undefined);
 assert.doesNotMatch(line.entryHint,/朱老头|毒宗|门路/);
 assert.equal(resolveAvailableLines(undefined,{},line.anchorEventIds).find(x=>x.id==='heimohai').name,'黑魔海');
 for(const chapter of [65,86,106,120])assert.equal(secondaryLineDisplayName(line,{axisAnchor:`第${chapter}章`}), '黑魔海');
 for (const chapter of [121,122,124,125,126]) assert.equal(secondaryLineDisplayName(line,{axisAnchor:`第${chapter}章`}),'黑魔海／毒宗');
 assert.ok(line.nodes.some(x=>x.eventId===chat));
 assert.ok(line.nodes.some(x=>x.status==='pending' && /太一经/.test(x.reviewSummary)));
});
test('chapter65 chat is optional, settles once, leaves next rail event incomplete and expires on departure',async()=>{
 const {createMinimalSaveDataV3}=await loadTs('../src/utils/dataRepair.ts');
 const {buildStrictScenarioInitialization,applyStrictScenarioInitializationToSave}=await loadTs('../src/modules/scenarioMods/strictInitializer.ts');
 const {getCurrentStoryExplorationActions,recordStoryEventStructuredAction,advanceScenarioRuntime,getScenarioFocusEvent}=await loadTs('../src/modules/scenarioMods/runtime.ts');
 const d=JSON.parse(await readFile(new URL(`../src/modules/scenarioMods/builtins/data/${sid}.json`,import.meta.url),'utf8'));
 const save=applyStrictScenarioInitializationToSave(createMinimalSaveDataV3(),buildStrictScenarioInitialization(d));
 const rt=save.世界.状态.剧本模组;
 rt.currentChapterId='lcq.chapter.s04b_lingfei_baiyi_crisis_aftermath';
 rt.activeEventIds=['lcq.event.s04b_lingfei_baiyi_crisis_14',chat];
 rt.flags['event.s04b_lingfei_baiyi_crisis_13.done']=true;
 save.角色.位置.描述='南荒·白夷族';
 const event=rt.events.find(e=>e.id===chat);
 assert.equal(event.critical,false);assert.equal(event.exploration.role,'seed');
 const action=event.playerCompletionContract.actions[0];
 assert.equal(action.forceFixed,true);
 assert.match(action.fallbackText,/长翅膀的鸟人/);assert.match(action.fallbackText,/无字信笺/);assert.doesNotMatch(action.fallbackText,/毒宗/);
 const {getCanonRailProfile}=await loadTs('../src/modules/scenarioMods/canonRail.ts');
 const rail=getCanonRailProfile(rt);
 assert.ok(!rail.orderedEventIds.includes(chat));
 const nextId='lcq.event.s04b_lingfei_baiyi_crisis_14';
 rt.completedEventIds=rail.orderedEventIds.slice(0,rail.orderedEventIds.indexOf(nextId));
 for(const id of rt.completedEventIds)rt.flags[`event.${id.replace('lcq.event.','')}.done`]=true;
 rt.activeEventIds=[nextId];
 const refreshed=advanceScenarioRuntime(save).saveData;
 assert.ok(refreshed.世界.状态.剧本模组.activeEventIds.includes(chat));
 assert.equal(getScenarioFocusEvent(refreshed.世界.状态.剧本模组).id,nextId);
 rt.activeEventIds.push(chat);
 const actions=getCurrentStoryExplorationActions(save);
 assert.equal(actions.length,1);
 save.角色.位置.描述='南荒·碧鲮族';assert.equal(getCurrentStoryExplorationActions(save).length,0);
 save.角色.位置.描述='南荒·白夷族';
 const result=recordStoryEventStructuredAction(save,actions[0]);
 assert.equal(result.completed,true);
 assert.equal(rt.eventActionStates['lcq.event.s04b_lingfei_baiyi_crisis_14']?.readyAtTurn,undefined);
 assert.equal(getCurrentStoryExplorationActions(save).length,0);
 delete rt.eventActionStates[chat];rt.flags['event.s04b_lingfei_baiyi_crisis_14.done']=true;
 assert.equal(getCurrentStoryExplorationActions(save).length,0);
});
