import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {loadTs} from './loadTs.mjs';
const mod=s=>JSON.parse(fs.readFileSync(new URL(`../src/modules/scenarioMods/builtins/data/${s}.json`,import.meta.url)));
const registry=JSON.parse(fs.readFileSync(new URL('../src/modules/scenarioMods/builtins/character-registry.json',import.meta.url)));
test('Duan opening card has only seven already-happened memories and no death/beast appearance',()=>{const c=mod('lcq.stage_01').canon.characters.find(c=>c.id==='lcq.character.duan_qiang');assert.equal(c.profile.memories.length,7);assert.doesNotMatch(JSON.stringify(c),/已故|已死亡|在草原上死亡|长箭射穿|兽鬃|下颌骨/);const r=registry.characters.find(c=>c.id=== 'lcq.character.duan_qiang');assert.doesNotMatch(JSON.stringify(r),/已故|已死亡|在草原上死亡|长箭射穿|兽鬃|下颌骨/);});
test('initial Qingyu memories do not pre-set later death, ice gu or encounters',()=>{const a=mod('lcq.stage_01'),b=mod('lcq.stage_02');const p=(m,n)=>m.canon.characters.find(c=>c.name===n).profile;assert.doesNotMatch(JSON.stringify(p(a,'程宗扬').memories),/遇到王哲|被段强拖累/);assert.doesNotMatch(JSON.stringify(p(a,'王哲')),/已死亡|传授程宗扬九阳|一同战死/);assert.doesNotMatch(a.canon.characters.find(c=>c.name==='月霜').role,/遗女|雪隼/);assert.doesNotMatch(JSON.stringify(p(b,'程宗扬').memories),/冰蛊|结识凝羽|前往南荒/);assert.equal(p(a,'凝羽').memories.length,0);assert.equal(p(b,'凝羽').memories.length,0);});
test('misty daylight scene and later mushroom night are event scoped',()=>{const m=mod('lcq.stage_04');assert.match(m.canon.locations.find(l=>l.id==='liuchao.location.shan_jian').description,/白天.*黎明起的浓雾/);assert.equal(m.scenario.chapters[0].eventIds[0],'lcq.event.s04_02');for(const id of ['s04_02','s04_03'])for(const a of m.scenario.events.find(e=>e.id===`lcq.event.${id}`).playerCompletionContract.actions)assert.equal(a.dayPart,'白天');assert.equal(m.scenario.events.find(e=>e.id==='lcq.event.s04_01').playerCompletionContract.actions[0].dayPart,'夜');});
const intent=await loadTs('../src/modules/scenarioMods/naturalIntentRouter.ts'),rt=await loadTs('../src/modules/scenarioMods/runtime.ts'),init=await loadTs('../src/modules/scenarioMods/strictInitializer.ts'),repair=await loadTs('../src/utils/dataRepair.ts');
function coldSave(prepared=true){const s=init.applyStrictScenarioInitializationToSave(repair.createMinimalSaveDataV3(),init.buildStrictScenarioInitialization(mod('lcq.stage_02')));s.系统.扩展.清羽记开局={kind:'qingyu-demo-v1'};const r=s.世界.状态.剧本模组;for(const e of r.events)if(e.id!=='lcq.event.ningyu_regicide_offer'){r.completedEventIds.push(e.id);for(const c of e.completion||[])if(c.path.startsWith('flags.'))r.flags[c.path.slice(6)]=c.value;}r.activeEventIds=['lcq.event.ningyu_regicide_offer'];s.角色.位置.描述='中州·南荒途中·商队宿处';if(prepared){const first=rt.getCurrentStoryEventActions(s)[0];assert.ok(first);rt.recordStoryEventStructuredAction(s,first);r.worldTurn++;}return s;}
for(const text of ['这股不属于你的寒气是谁留下的？','你身上寒气是怎么来的？','我与你行功，摸清寒气根源，请你说明','是不是西门庆留下的？','是不是曾控制你的外人留下的？'])test(`cold-source inquiry accepts player intent without requiring answer: ${text}`,async()=>{const s=coldSave();const out=await intent.resolveNaturalIntent({saveData:s,playerText:text,generate:async()=>JSON.stringify({source:'event_engine',eventId:'lcq.event.ningyu_regicide_offer',actionId:'trace_ningyu_cold_qi_source',evidence:text,certainty:'high'})});assert.equal(out.kind,'matched',JSON.stringify({out,candidates:intent.listNaturalIntentCandidates(s)}));assert.equal(out.selection.actionId,'trace_ningyu_cold_qi_source');});
for(const text of ['寒气就是冰蛊','是凝羽自己留的','是苏妲己留下的'])test(`wrong-source proposal never settles: ${text}`,async()=>{const s=coldSave();const out=await intent.resolveNaturalIntent({saveData:s,playerText:text,generate:async()=>JSON.stringify({source:'event_engine',eventId:'lcq.event.ningyu_regicide_offer',actionId:'trace_ningyu_cold_qi_source',evidence:text,certainty:'high'})});assert.notEqual(out.kind,'matched');assert.equal(s.世界.状态.剧本模组.eventActionStates['lcq.event.ningyu_regicide_offer'].attemptCount,1);});
test('source inquiry cannot bypass first-step preparation',()=>{assert.ok(!rt.getCurrentStoryEventActions(coldSave(false)).some(a=>a.actionId==='trace_ningyu_cold_qi_source'));});
