/** Generated by scripts/build-canon-rail-profiles.mjs; author data lives in JSON. */
import data from './canonRailProfiles.generated.json';
import type { CanonRailProfile } from './canonRail';
export const GENERATED_CANON_RAIL_PROFILES: CanonRailProfile[] = data;
